// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ilfxfggmyrmblmrqjrvl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlsZnhmZ2dteXJtYmxtcnFqcnZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0NzgzODIsImV4cCI6MjA1ODA1NDM4Mn0.LzUQ6MhDh3tG-L9X1J5oHNvXxcNAC1Fg-jNenCaDAhQ";

// Create a singleton instance for the supabase client to ensure persistence
let supabaseInstance: ReturnType<typeof createClient<Database>> | null = null;

const getSupabaseClient = () => {
  if (!supabaseInstance) {
    console.log("Creating new Supabase client instance");
    supabaseInstance = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        persistSession: true,
        autoRefreshToken: true,
        storageKey: 'life-quest-supabase-auth',
        detectSessionInUrl: true,
        flowType: 'pkce',
        storage: {
          getItem: (key) => {
            try {
              const item = localStorage.getItem(key);
              return item;
            } catch (error) {
              console.error('Error reading from localStorage:', error);
              return null;
            }
          },
          setItem: (key, value) => {
            try {
              localStorage.setItem(key, value);
            } catch (error) {
              console.error('Error writing to localStorage:', error);
            }
          },
          removeItem: (key) => {
            try {
              localStorage.removeItem(key);
            } catch (error) {
              console.error('Error removing from localStorage:', error);
            }
          },
        },
      },
      global: {
        headers: {
          'X-Client-Info': 'life-quest-web',
        },
      },
      realtime: {
        params: {
          eventsPerSecond: 2,
        },
      },
    });

    // Add auth state change listener
    supabaseInstance.auth.onAuthStateChange((event, session) => {
      console.log('Auth state changed:', event, 'Session:', session ? 'exists' : 'null');
      
      if (event === 'SIGNED_OUT' || event === 'USER_DELETED') {
        // Clear any cached data
        localStorage.removeItem('gameDataCache');
        localStorage.removeItem('lastSyncTime');
      }
    });
  } else {
    console.log("Using existing Supabase client instance");
  }
  return supabaseInstance;
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = getSupabaseClient();
