// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { toast } from 'sonner';

const SUPABASE_URL = "https://ilfxfggmyrmblmrqjrvl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlsZnhmZ2dteXJtYmxtcnFqcnZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0NzgzODIsImV4cCI6MjA1ODA1NDM4Mn0.LzUQ6MhDh3tG-L9X1J5oHNvXxcNAC1Fg-jNenCaDAhQ";

// Create a singleton instance for the supabase client to ensure persistence
let supabaseInstance: ReturnType<typeof createClient<Database>> | null = null;
let initializationStartTime: number | null = null;

const getSupabaseClient = () => {
  if (!supabaseInstance) {
    console.log("Creating new Supabase client instance");
    initializationStartTime = Date.now();
    
    // Validate URL and key
    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      console.error("Missing Supabase configuration");
      toast.error("Error initializing database connection");
      throw new Error("Missing Supabase configuration");
    }

    try {
      // Load cached session first if available
      const cachedSession = localStorage.getItem('life-quest-supabase-auth');
      if (cachedSession) {
        console.log("Found cached session data");
      }

      supabaseInstance = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
        auth: {
          persistSession: true,
          autoRefreshToken: true,
          storageKey: 'life-quest-supabase-auth',
          detectSessionInUrl: true,
          flowType: 'pkce',
          storage: {
            getItem: (key) => {
              try {
                const item = localStorage.getItem(key);
                return item;
              } catch (error) {
                console.error('Error reading from localStorage:', error);
                return null;
              }
            },
            setItem: (key, value) => {
              try {
                localStorage.setItem(key, value);
              } catch (error) {
                console.error('Error writing to localStorage:', error);
                toast.error("Failed to save authentication data");
              }
            },
            removeItem: (key) => {
              try {
                localStorage.removeItem(key);
              } catch (error) {
                console.error('Error removing from localStorage:', error);
              }
            },
          },
        },
        global: {
          headers: {
            'X-Client-Info': 'life-quest-web',
          },
        },
        realtime: {
          params: {
            eventsPerSecond: 2,
          },
        },
        // Optimize initial connection
        db: {
          schema: 'public',
          // Add performance monitoring
          transformResponse: (response) => {
            const endTime = Date.now();
            if (initializationStartTime) {
              console.log(`Supabase response time: ${endTime - initializationStartTime}ms`);
            }
            return response;
          },
        },
      });

      // Add auth state change listener with integrated error handling
      supabaseInstance.auth.onAuthStateChange((event, session) => {
        const timestamp = new Date().toISOString();
        console.log(`[${timestamp}] Auth state changed:`, event, 'Session:', session ? 'exists' : 'null');
        
        // Handle authentication errors
        if (event === 'USER_DELETED' || event === 'SIGNED_OUT') {
          // Clear any cached data
          localStorage.removeItem('gameDataCache');
          localStorage.removeItem('lastSyncTime');
          console.log('Cleared cached data due to auth state change');
          
          if (event === 'USER_DELETED') {
            console.error('User account was deleted');
            toast.error("Authentication error. Please sign in again.");
          }
        }

        if (event === 'TOKEN_REFRESHED') {
          console.log('Auth token refreshed successfully');
        } else if (event === 'TOKEN_REFRESH_FAILED') {
          console.error('Failed to refresh authentication token');
          toast.error("Session expired. Please sign in again.");
        }

        if (event === 'SIGNED_IN') {
          // Log initialization time
          if (initializationStartTime) {
            const totalTime = Date.now() - initializationStartTime;
            console.log(`Total initialization time: ${totalTime}ms`);
            initializationStartTime = null;
          }

          // Validate the session
          if (session) {
            const expiresAt = session.expires_at;
            if (expiresAt) {
              const expiresIn = new Date(expiresAt * 1000).getTime() - Date.now();
              console.log(`Session expires in ${Math.round(expiresIn / 1000 / 60)} minutes`);
              
              // Warn user if session is close to expiring
              if (expiresIn < 5 * 60 * 1000) { // Less than 5 minutes
                toast.warning("Your session will expire soon. Please refresh the page.");
              }
            }
          }
        }
      });

    } catch (error) {
      const initTime = initializationStartTime ? Date.now() - initializationStartTime : 'unknown';
      console.error(`Error creating Supabase client (after ${initTime}ms):`, error);
      toast.error("Failed to initialize database connection");
      throw error;
    }
  } else {
    console.log("Using existing Supabase client instance");
  }

  // Verify the client is properly initialized
  if (!supabaseInstance) {
    console.error("Failed to initialize Supabase client");
    toast.error("Database connection error");
    throw new Error("Failed to initialize Supabase client");
  }

  return supabaseInstance;
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = getSupabaseClient();
